brian-greeson/adopt_dont_shop_paired

- app/controllers/shelter_reviews_controller.rb
- app/models/shelter.rb
- app/models/shelter_review.rb
- app/views/layouts/application.html.erb
- app/views/shelter_reviews/new.html.erb
- app/views/shelters/show.html.erb
- config/routes.rb
- db/migrate/20200318010053_create_shelters.rb
- db/migrate/20200321170511_create_pet.rb
- db/migrate/20200325013539_create_shelter_review.rb
- db/schema.rb
- spec/features/shelter_reviews/shelter_review_show_spec.rb
- spec/models/shelter_review_spec.rb
- Create ShelterReviewsController
- Create ShelterReview Model
- Add new and create methods to ShelterReviewsController
- Add ShelterReviews creation form
- Add ShelterReviews to Shelter show page
- Add happy and sad paths for ShelterReview creation
> Shelter Review Creation

- spec/features/shelter_reviews/shelter_review_show_spec.rb
- Uncomment out ShelterReviews and pass test for sad path edge case
> Uncomment out test for ShelterReviews

- app/controllers/shelter_reviews_controller.rb
- app/views/shelter_reviews/edit.html.erb
- app/views/shelters/show.html.erb
- config/routes.rb
- spec/features/shelter_reviews/edit_spec.rb
- Add ShelterReview edit functionality
- Add ShelterReview sad path testing
- Add sad path flash message for incomplete form
> Add ShelterReview edit and Update Functionality

- app/controllers/shelter_reviews_controller.rb
- app/views/shelters/show.html.erb
- config/routes.rb
- spec/features/shelter_reviews/delete_spec.rb
- Added destroy functionality to shelter reviews controller
- Updated routes with delete review and added route prefixes
- Updated shelter show page with delete linky
> Destroy reviews

- app/controllers/pet_applications_controller.rb
- app/models/application_pet.rb
- app/models/favorite.rb
- app/models/pet.rb
- app/models/pet_application.rb
- app/views/favorite/index.html.erb
- app/views/pet_applications/new.html.erb
- config/routes.rb
- db/migrate/20200328235903_create_pet_application.rb
- db/migrate/20200329001214_create_application_pets.rb
- db/schema.rb
- spec/features/pet_applications/new_spec.rb
- spec/models/application_pet_spec.rb
- spec/models/favorite_spec.rb
- spec/models/pet_application_spec.rb
- Added PetApplicationsController
- Added pet application form
- Added PetApplication model
- Added pet application sad path testing
- Added PetApplications table
- Added ApplicationPets join table
- Added ApplicationPet model 
- Added validation and relationship testing to all new models; updated validations and relationships for existing models as needed
- Created route to new application form
- Added model methods and testing for .pets, .add_pet, remove_pet, .remove_pets
> New Pet Application Functionality

- app/controllers/pet_applications_controller.rb
- app/models/pet_application.rb
- spec/features/pet_applications/new_spec.rb
- spec/models/pet_application_spec.rb
- Add validation for pet_ids in the PetApplication model, triggering sad path if a pet is not selected when creating an application
- Fixed PetApplicationsController to only remove favorite pets when application is received
> Add Validation to Pet Applications

- app/controllers/pet_applications_controller.rb
- app/views/pet_applications/show.html.erb
- config/routes.rb
- spec/features/pet_applications/show_spec.rb
- spec/models/pet_application_spec.rb
- Add route to application show page
- Add show method to PetApplications Controller
- Add PetApplications Show page view
> Application Show Page

- app/controllers/pet_applications_controller.rb
- app/controllers/pets_controller.rb
- app/models/pet_application.rb
- app/views/pet_applications/index.html.erb
- app/views/pets/show.html.erb
- config/routes.rb
- spec/features/pets/show_spec.rb
- spec/models/pet_application_spec.rb
- Add PetApplications Index functionality
- Add PetApplications index view
- Add View Applications link on Pet show page
- Add route for PetApplications index
- Add for_pets method to PetApplication model
> Applications Index Page

- app/controllers/pet_applications_controller.rb
- app/views/pet_applications/show.html.erb
- app/views/pets/show.html.erb
- config/routes.rb
- db/migrate/20200330025303_add_column_applicant_to_pets.rb
- db/schema.rb
- spec/features/pet_applications/show_spec.rb
- Added applicant column to pets table
- Added applicant on pet show page if set
- Added approve application controller action
- Added route for application approve action
> Approve applications

- app/controllers/favorite_controller.rb
- Updated favorite controller index action to use model `.pets` method
> Update favorite controller to use model method pets

- spec/features/pet_applications/show_spec.rb
- Added expects to test approving multiple pets on one application
- Fixes: #24
> Add edge case testing for adding multiple pets from same app

- app/controllers/pets_controller.rb
- app/controllers/shelter_reviews_controller.rb
- app/controllers/shelters_controller.rb
- config/routes.rb
- db/migrate/20200321170511_create_pet.rb
- db/migrate/20200330195347_changeadoption_status_to_string_in_pets.rb
- db/schema.rb
- spec/features/favorite/add_pet_spec.rb
- spec/features/shelters/create_shelter_pet_spec.rb
- Add strong params in PetApplications controller
- Utilize strong params in all controllers 
- Update all ID route calls to be more specific
- Modified all controllers to use new IDs
- Fixed default value migration on the Pets table (adoption_status)
> Base Code Refactor

- app/controllers/application_pets_controller.rb
- app/controllers/pet_applications_controller.rb
- app/controllers/pets_controller.rb
- app/models/application_pet.rb
- app/models/pet.rb
- app/views/pets/show.html.erb
- config/routes.rb
- db/migrate/20200329001214_create_application_pets.rb
- db/migrate/20200330214848_remove_applicant_from_pets.rb
- db/migrate/20200330214901_remove_adoption_status_from_pets.rb
- db/migrate/20200330215025_add_status_to_application_pets.rb
- db/migrate/20200330215918_change_column_status_in_application_pets.rb
- db/migrate/20200330232525_change_column_status_in_application_pet.rb
- db/schema.rb
- spec/features/favorite/add_pet_spec.rb
- spec/features/pet_applications/show_spec.rb
- spec/features/pets/edit_spec.rb
- spec/features/pets/show_spec.rb
- spec/features/shelters/create_shelter_pet_spec.rb
- spec/models/application_pet_spec.rb
- spec/models/favorite_spec.rb
- spec/models/pet_application_spec.rb
- spec/models/pet_spec.rb
- spec/models/shelter_review_spec.rb
- spec/models/shelter_spec.rb
- Removed unused controller actions
- Moved model logic from controllers to models
- Improved formatting
- Removed reference to unused pet columns
- Removed adoption data from pets table
- Add application status to applications join table
- Updated application status default value
- Updated routes 
fixes #58
> Pet application refactor

- app/views/pet_applications/show.html.erb
- spec/features/pet_applications/index_spec.rb
- Remove 'Approve' link from Application Show page when an application is pending
> Pet Can only Have One Approved Application

- spec/features/shelters/show_spec.rb
- Added test to shelter show spec
> Add test to verify that a shelter's pets are deleted with it

- app/controllers/shelters_controller.rb
- app/views/layouts/application.html.erb
- spec/features/shelters/edit_spec.rb
- spec/features/shelters/user_can_create_new_shelter_spec.rb
- Added logic to application view to show missing from fields
- Added check in create shelter for incomplete form
- Update and Create now send error message to flash message view when missing fields
- Improved formatting
> Indicate missing fields

- app/models/shelter.rb
- app/views/shelters/show.html.erb
- spec/features/shelter_reviews/shelter_review_show_spec.rb
- spec/features/shelters/show_spec.rb
- spec/models/shelter_spec.rb
- Add MVC for shelter stats
- Average rating
- Total Pets
- Total Applications for all pets
> Shelter stats

- app/models/pet.rb
- app/views/pets/show.html.erb
- spec/features/pets/show_spec.rb
- spec/models/pet_spec.rb
- Add Logic to hide delete button in view
- Update Pet approved_application method to return false if there are no approved applications for pet
- Added test that delete button is hidden from pet show page if pet has approved application
> Can't delete approved pet

- app/controllers/pets_controller.rb
- spec/features/favorite/index_spec.rb
- spec/features/pets/delete_spec.rb
- Add test that deleted pet is removed from favorites and favorite counter is decremented
- Add remove favorite pet logic to destroy action of pets controller
> Delete pet removes favorite

- app/controllers/pets_controller.rb
- app/controllers/shelters_controller.rb
- spec/features/pets/edit_spec.rb
- spec/features/shelters/create_shelter_pet_spec.rb
- Add test that user is notified of missing fields when creating or updating pets
- Added Controller logic to send flash messages with missing fields
- Fixed render action in shelters controller update action @SMJ289
> Incomplete field message for pet

- spec/models/pet_spec.rb
- Addes test for Pet model method approved_application.
- Method returns the approved application for pet
- Returns false if no approved application present
- Closes: #68
> Add model test for pet method approved application

- spec/features/favorite/add_pet_spec.rb
- spec/features/favorite/index_spec.rb
- spec/features/pet_applications/index_spec.rb
- spec/features/pet_applications/new_spec.rb
- spec/features/pet_applications/show_spec.rb
- spec/features/pets/delete_spec.rb
- spec/features/pets/edit_spec.rb
- spec/features/pets/index_spec.rb
- spec/features/pets/show_spec.rb
- spec/features/shelter_reviews/edit_spec.rb
- spec/features/shelter_reviews/shelter_review_show_spec.rb
- spec/features/shelters/create_shelter_pet_spec.rb
- spec/features/shelters/edit_spec.rb
- spec/features/shelters/index_spec.rb
- spec/features/shelters/pet_index_by_shelter_spec.rb
- spec/features/shelters/show_spec.rb
- spec/features/shelters/user_can_create_new_shelter_spec.rb
- spec/models/application_pet_spec.rb
- spec/models/pet_application_spec.rb
- spec/models/pet_spec.rb
- Removed empty lines
- Updated code style to be more consistent
- Purely cosmetic, No functionality changes
- No changes to views
> Removed empty lines

- app/assets/stylesheets/application.css
- app/views/favorite/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pet_applications/index.html.erb
- app/views/pets/index.html.erb
- app/views/pets/show.html.erb
- app/views/shelters/index.html.erb
- app/views/shelters/pet_index.html.erb
- app/views/shelters/show.html.erb
- Update styling throughout app
- Add to stylesheet
> Update Styling 
